"""Management command to seed the badge catalog idempotently."""

from django.core.management.base import BaseCommand

from social.models import Badge


BADGE_CATALOG = [
    # ── Universal: Streak milestones ──────────────────────────────────────────
    {
        "key": "streak_7",
        "name": "Week Warrior",
        "description": "Maintain a 7-day streak.",
        "tier": "bronze",
        "path_specific": "",
        "icon_name": "flame_7",
    },
    {
        "key": "streak_30",
        "name": "Month of Mastery",
        "description": "Maintain a 30-day streak.",
        "tier": "silver",
        "path_specific": "",
        "icon_name": "flame_30",
    },
    {
        "key": "streak_100",
        "name": "Century Streak",
        "description": "Maintain a 100-day streak.",
        "tier": "gold",
        "path_specific": "",
        "icon_name": "flame_100",
    },
    {
        "key": "streak_365",
        "name": "Year of Discipline",
        "description": "Maintain a 365-day streak — one full year.",
        "tier": "legendary",
        "path_specific": "",
        "icon_name": "flame_365",
    },
    # ── Universal: Level milestones ───────────────────────────────────────────
    {
        "key": "level_5",
        "name": "Novice Adventurer",
        "description": "Reach Level 5.",
        "tier": "bronze",
        "path_specific": "",
        "icon_name": "star_5",
    },
    {
        "key": "level_10",
        "name": "Seasoned Challenger",
        "description": "Reach Level 10.",
        "tier": "silver",
        "path_specific": "",
        "icon_name": "star_10",
    },
    {
        "key": "level_20",
        "name": "Veteran Practitioner",
        "description": "Reach Level 20.",
        "tier": "gold",
        "path_specific": "",
        "icon_name": "star_20",
    },
    {
        "key": "level_30",
        "name": "Elite Disciplinarian",
        "description": "Reach Level 30.",
        "tier": "platinum",
        "path_specific": "",
        "icon_name": "star_30",
    },
    # ── Universal: Cross-path title badges ────────────────────────────────────
    {
        "key": "cross_path_warrior_sage",
        "name": "Warrior-Sage",
        "description": "Active on 2 paths simultaneously.",
        "tier": "silver",
        "path_specific": "",
        "icon_name": "cross_path_2",
    },
    {
        "key": "cross_path_optimized_human",
        "name": "Optimized Human",
        "description": "Active on 3 paths simultaneously.",
        "tier": "gold",
        "path_specific": "",
        "icon_name": "cross_path_3",
    },
    {
        "key": "cross_path_complete_human",
        "name": "Complete Human",
        "description": "Active on 4 paths simultaneously.",
        "tier": "platinum",
        "path_specific": "",
        "icon_name": "cross_path_4",
    },
    {
        "key": "cross_path_renaissance_human",
        "name": "Renaissance Human",
        "description": "Active on all 5 paths simultaneously.",
        "tier": "legendary",
        "path_specific": "",
        "icon_name": "cross_path_5",
    },
    # ── Universal: Weekly boss ────────────────────────────────────────────────
    {
        "key": "boss_slayer_first",
        "name": "Boss Slayer",
        "description": "Defeat your first Weekly Boss.",
        "tier": "bronze",
        "path_specific": "",
        "icon_name": "boss_skull",
    },
    {
        "key": "boss_slayer_5",
        "name": "Boss Hunter",
        "description": "Defeat 5 Weekly Bosses.",
        "tier": "silver",
        "path_specific": "",
        "icon_name": "boss_skull_5",
    },
    {
        "key": "boss_slayer_10",
        "name": "Boss Conqueror",
        "description": "Defeat 10 Weekly Bosses.",
        "tier": "gold",
        "path_specific": "",
        "icon_name": "boss_skull_10",
    },
    # ── Fitness Warrior ───────────────────────────────────────────────────────
    {
        "key": "fw_first_quest",
        "name": "First Blood",
        "description": "Complete your very first Fitness Warrior quest.",
        "tier": "bronze",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_fist",
    },
    {
        "key": "fw_streak_7",
        "name": "Iron Week",
        "description": "Complete a 7-day Fitness Warrior streak.",
        "tier": "bronze",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_iron_7",
    },
    {
        "key": "fw_streak_30",
        "name": "Iron Month",
        "description": "Complete a 30-day Fitness Warrior streak.",
        "tier": "silver",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_iron_30",
    },
    {
        "key": "fw_level_10",
        "name": "Forged Body",
        "description": "Reach Level 10 on the Fitness Warrior path.",
        "tier": "silver",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_body",
    },
    {
        "key": "fw_level_20",
        "name": "Battle-Hardened",
        "description": "Reach Level 20 on the Fitness Warrior path.",
        "tier": "gold",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_warrior",
    },
    {
        "key": "fw_boss_week_1",
        "name": "Warrior's Trial",
        "description": "Defeat the first Fitness Warrior Weekly Boss.",
        "tier": "silver",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_boss",
    },
    {
        "key": "fw_boss_conqueror",
        "name": "Apex Warrior",
        "description": "Defeat 5 Fitness Warrior Weekly Bosses.",
        "tier": "gold",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_apex",
    },
    {
        "key": "fw_100_completions",
        "name": "Centurion Warrior",
        "description": "Complete 100 Fitness Warrior quests.",
        "tier": "gold",
        "path_specific": "fitness_warrior",
        "icon_name": "fw_100",
    },
    # ── Mindset Sage ──────────────────────────────────────────────────────────
    {
        "key": "ms_first_quest",
        "name": "Inner Awakening",
        "description": "Complete your very first Mindset Sage quest.",
        "tier": "bronze",
        "path_specific": "mindset_sage",
        "icon_name": "ms_lotus",
    },
    {
        "key": "ms_first_freedom_token",
        "name": "Freedom Earned",
        "description": "Earn your first Freedom Day Token.",
        "tier": "bronze",
        "path_specific": "mindset_sage",
        "icon_name": "ms_token",
    },
    {
        "key": "ms_streak_7",
        "name": "Seven Mindful Days",
        "description": "Complete a 7-day Mindset Sage streak.",
        "tier": "bronze",
        "path_specific": "mindset_sage",
        "icon_name": "ms_7",
    },
    {
        "key": "ms_streak_30",
        "name": "Month of Clarity",
        "description": "Complete a 30-day Mindset Sage streak.",
        "tier": "silver",
        "path_specific": "mindset_sage",
        "icon_name": "ms_30",
    },
    {
        "key": "ms_wisdom_10",
        "name": "Wisdom Seeker",
        "description": "Write 10 wisdom log entries.",
        "tier": "bronze",
        "path_specific": "mindset_sage",
        "icon_name": "ms_scroll",
    },
    {
        "key": "ms_wisdom_50",
        "name": "Sage Mind",
        "description": "Write 50 wisdom log entries.",
        "tier": "silver",
        "path_specific": "mindset_sage",
        "icon_name": "ms_sage",
    },
    {
        "key": "ms_dark_night_1",
        "name": "Facing the Shadow",
        "description": "Complete your first Dark Night entry.",
        "tier": "silver",
        "path_specific": "mindset_sage",
        "icon_name": "ms_shadow",
    },
    {
        "key": "ms_level_10",
        "name": "Mindful Practitioner",
        "description": "Reach Level 10 on the Mindset Sage path.",
        "tier": "silver",
        "path_specific": "mindset_sage",
        "icon_name": "ms_level10",
    },
    {
        "key": "ms_boss_week_1",
        "name": "Sage's Challenge",
        "description": "Defeat the first Mindset Sage Weekly Boss.",
        "tier": "silver",
        "path_specific": "mindset_sage",
        "icon_name": "ms_boss",
    },
    {
        "key": "ms_100_completions",
        "name": "Centurion Sage",
        "description": "Complete 100 Mindset Sage quests.",
        "tier": "gold",
        "path_specific": "mindset_sage",
        "icon_name": "ms_100",
    },
    # ── Health Alchemist ──────────────────────────────────────────────────────
    {
        "key": "ha_first_quest",
        "name": "First Brew",
        "description": "Complete your very first Health Alchemist quest.",
        "tier": "bronze",
        "path_specific": "health_alchemist",
        "icon_name": "ha_flask",
    },
    {
        "key": "ha_elixir_day7",
        "name": "Elixir Alchemist",
        "description": "Fill your elixir for 7 consecutive days.",
        "tier": "silver",
        "path_specific": "health_alchemist",
        "icon_name": "ha_elixir",
    },
    {
        "key": "ha_triple_brew",
        "name": "Triple Transmutation",
        "description": "Complete 3 elixir brews.",
        "tier": "silver",
        "path_specific": "health_alchemist",
        "icon_name": "ha_triple",
    },
    {
        "key": "ha_master_formula",
        "name": "Master Formula",
        "description": "Complete 7 elixir brews.",
        "tier": "gold",
        "path_specific": "health_alchemist",
        "icon_name": "ha_master",
    },
    {
        "key": "ha_streak_7",
        "name": "Seven Days Clean",
        "description": "Complete a 7-day Health Alchemist streak.",
        "tier": "bronze",
        "path_specific": "health_alchemist",
        "icon_name": "ha_7",
    },
    {
        "key": "ha_streak_30",
        "name": "Transmuted Life",
        "description": "Complete a 30-day Health Alchemist streak.",
        "tier": "silver",
        "path_specific": "health_alchemist",
        "icon_name": "ha_30",
    },
    {
        "key": "ha_level_10",
        "name": "Alchemist's Apprentice",
        "description": "Reach Level 10 on the Health Alchemist path.",
        "tier": "silver",
        "path_specific": "health_alchemist",
        "icon_name": "ha_level10",
    },
    {
        "key": "ha_boss_week_1",
        "name": "Alchemist's Trial",
        "description": "Defeat the first Health Alchemist Weekly Boss.",
        "tier": "silver",
        "path_specific": "health_alchemist",
        "icon_name": "ha_boss",
    },
    {
        "key": "ha_100_completions",
        "name": "Centurion Alchemist",
        "description": "Complete 100 Health Alchemist quests.",
        "tier": "gold",
        "path_specific": "health_alchemist",
        "icon_name": "ha_100",
    },
    # ── Discipline Knight ─────────────────────────────────────────────────────
    {
        "key": "dk_first_quest",
        "name": "Squire's Oath",
        "description": "Complete your very first Discipline Knight quest.",
        "tier": "bronze",
        "path_specific": "discipline_knight",
        "icon_name": "dk_shield",
    },
    {
        "key": "dk_armor_boots",
        "name": "Boots of Discipline",
        "description": "Earn your first armor piece — the Forged Boots (7-day streak).",
        "tier": "bronze",
        "path_specific": "discipline_knight",
        "icon_name": "dk_boots",
    },
    {
        "key": "dk_armor_full",
        "name": "Fully Armored Knight",
        "description": "Complete the full Knight armor set (42-day streak).",
        "tier": "legendary",
        "path_specific": "discipline_knight",
        "icon_name": "dk_armor_full",
    },
    {
        "key": "dk_streak_7",
        "name": "Knight's Vigil",
        "description": "Complete a 7-day Discipline Knight streak.",
        "tier": "bronze",
        "path_specific": "discipline_knight",
        "icon_name": "dk_vigil",
    },
    {
        "key": "dk_streak_30",
        "name": "Knight's Resolve",
        "description": "Complete a 30-day Discipline Knight streak.",
        "tier": "silver",
        "path_specific": "discipline_knight",
        "icon_name": "dk_resolve",
    },
    {
        "key": "dk_weekly_report_1",
        "name": "First Debrief",
        "description": "Receive your first Knight Weekly Report.",
        "tier": "bronze",
        "path_specific": "discipline_knight",
        "icon_name": "dk_report",
    },
    {
        "key": "dk_level_10",
        "name": "Knight of the Order",
        "description": "Reach Level 10 on the Discipline Knight path.",
        "tier": "silver",
        "path_specific": "discipline_knight",
        "icon_name": "dk_order",
    },
    {
        "key": "dk_boss_week_1",
        "name": "Knight's Trial",
        "description": "Defeat the first Discipline Knight Weekly Boss.",
        "tier": "silver",
        "path_specific": "discipline_knight",
        "icon_name": "dk_boss",
    },
    {
        "key": "dk_100_completions",
        "name": "Centurion Knight",
        "description": "Complete 100 Discipline Knight quests.",
        "tier": "gold",
        "path_specific": "discipline_knight",
        "icon_name": "dk_100",
    },
    # ── Grind Visionary ───────────────────────────────────────────────────────
    {
        "key": "gv_first_quest",
        "name": "First Step",
        "description": "Complete your very first Grind Visionary quest.",
        "tier": "bronze",
        "path_specific": "grind_visionary",
        "icon_name": "gv_rocket",
    },
    {
        "key": "gv_first_dollar",
        "name": "First Dollar",
        "description": "Complete the First Dollar quest — your entrepreneurial journey begins.",
        "tier": "gold",
        "path_specific": "grind_visionary",
        "icon_name": "gv_dollar",
    },
    {
        "key": "gv_first_ten",
        "name": "First Ten",
        "description": "Complete the $10 Revenue Chain milestone.",
        "tier": "gold",
        "path_specific": "grind_visionary",
        "icon_name": "gv_ten",
    },
    {
        "key": "gv_first_hundred",
        "name": "First Hundred",
        "description": "Complete the $100 Revenue Chain milestone.",
        "tier": "platinum",
        "path_specific": "grind_visionary",
        "icon_name": "gv_hundred",
    },
    {
        "key": "gv_skill_tree_consistency",
        "name": "Consistency Node",
        "description": "Unlock the Consistency node in the Skill Tree.",
        "tier": "bronze",
        "path_specific": "grind_visionary",
        "icon_name": "gv_node_consistency",
    },
    {
        "key": "gv_skill_tree_execution",
        "name": "Execution Node",
        "description": "Unlock the Execution node in the Skill Tree.",
        "tier": "silver",
        "path_specific": "grind_visionary",
        "icon_name": "gv_node_execution",
    },
    {
        "key": "gv_skill_tree_shipping",
        "name": "Shipping Node",
        "description": "Unlock the Shipping node in the Skill Tree.",
        "tier": "silver",
        "path_specific": "grind_visionary",
        "icon_name": "gv_node_shipping",
    },
    {
        "key": "gv_skill_tree_audience",
        "name": "Audience Node",
        "description": "Unlock the Audience node in the Skill Tree.",
        "tier": "gold",
        "path_specific": "grind_visionary",
        "icon_name": "gv_node_audience",
    },
    {
        "key": "gv_skill_tree_monetization",
        "name": "Monetization Node",
        "description": "Unlock the Monetization node in the Skill Tree.",
        "tier": "gold",
        "path_specific": "grind_visionary",
        "icon_name": "gv_node_monetization",
    },
    {
        "key": "gv_skill_tree_scaling",
        "name": "Scaling Node",
        "description": "Unlock the Scaling node in the Skill Tree.",
        "tier": "platinum",
        "path_specific": "grind_visionary",
        "icon_name": "gv_node_scaling",
    },
    {
        "key": "gv_multiplier_2x",
        "name": "2× Visionary",
        "description": "Reach the maximum 2× XP multiplier.",
        "tier": "gold",
        "path_specific": "grind_visionary",
        "icon_name": "gv_2x",
    },
    {
        "key": "gv_streak_7",
        "name": "Visionary Week",
        "description": "Complete a 7-day Grind Visionary streak.",
        "tier": "bronze",
        "path_specific": "grind_visionary",
        "icon_name": "gv_7",
    },
    {
        "key": "gv_streak_30",
        "name": "Visionary Month",
        "description": "Complete a 30-day Grind Visionary streak.",
        "tier": "silver",
        "path_specific": "grind_visionary",
        "icon_name": "gv_30",
    },
    {
        "key": "gv_accountability_partner",
        "name": "Accountability Bond",
        "description": "Connect with an accountability partner.",
        "tier": "bronze",
        "path_specific": "grind_visionary",
        "icon_name": "gv_partner",
    },
    {
        "key": "gv_boss_week_1",
        "name": "Visionary's Trial",
        "description": "Defeat the first Grind Visionary Weekly Boss.",
        "tier": "silver",
        "path_specific": "grind_visionary",
        "icon_name": "gv_boss",
    },
    {
        "key": "gv_100_completions",
        "name": "Centurion Visionary",
        "description": "Complete 100 Grind Visionary quests.",
        "tier": "gold",
        "path_specific": "grind_visionary",
        "icon_name": "gv_100",
    },
]


class Command(BaseCommand):
    help = "Seed or refresh the badge catalog idempotently."

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for spec in BADGE_CATALOG:
            key = spec["key"]
            _, was_created = Badge.objects.update_or_create(
                key=key,
                defaults={
                    "name": spec["name"],
                    "description": spec["description"],
                    "tier": spec["tier"],
                    "path_specific": spec["path_specific"],
                    "icon_name": spec["icon_name"],
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Badge catalog seeded: {created} created, {updated} updated ({created + updated} total)."
        ))
