from django.urls import path

from .views import (
    AccountabilityRequestAcceptView,
    AccountabilityRequestListCreateView,
    AccountabilityRequestRejectView,
    ArmorLeaderboardView,
    FriendRemoveView,
    FriendRequestAcceptView,
    FriendRequestCancelView,
    FriendRequestDeclineView,
    FriendRequestListCreateView,
    FriendsListView,
    GroupFeedView,
    GroupJoinView,
    GroupLeaveView,
    GroupListCreateView,
    GroupMembershipListView,
    GlobalLeaderboardView,
    MultiplierStreakLeaderboardView,
    NotificationsMarkSeenView,
    NotificationsView,
    OutputMonthlyLeaderboardView,
    PlayerSearchView,
    PostCommentDetailView,
    PostCommentListCreateView,
    PostReactionView,
    PublicProfileView,
    SocialPostDetailView,
    SocialPostListCreateView,
    WeeklyLeaderboardView,
)

urlpatterns = [
    path("accountability/requests/", AccountabilityRequestListCreateView.as_view(), name="social-accountability-request-list-create"),
    path("accountability/requests/<int:request_id>/accept/", AccountabilityRequestAcceptView.as_view(), name="social-accountability-request-accept"),
    path("accountability/requests/<int:request_id>/reject/", AccountabilityRequestRejectView.as_view(), name="social-accountability-request-reject"),
    path("friends/requests/", FriendRequestListCreateView.as_view(), name="social-friend-request-list-create"),
    path("friends/requests/<int:request_id>/accept/", FriendRequestAcceptView.as_view(), name="social-friend-request-accept"),
    path("friends/requests/<int:request_id>/decline/", FriendRequestDeclineView.as_view(), name="social-friend-request-decline"),
    path("friends/requests/<int:request_id>/cancel/", FriendRequestCancelView.as_view(), name="social-friend-request-cancel"),
    path("friends/", FriendsListView.as_view(), name="social-friends-list"),
    path("friends/<int:player_id>/", FriendRemoveView.as_view(), name="social-friend-remove"),
    path("profiles/<str:identifier>/", PublicProfileView.as_view(), name="social-public-profile"),
    path("posts/", SocialPostListCreateView.as_view(), name="social-post-list-create"),
    path("posts/<int:post_id>/", SocialPostDetailView.as_view(), name="social-post-detail"),
    path("posts/<int:post_id>/comments/", PostCommentListCreateView.as_view(), name="social-post-comment-list-create"),
    path("posts/<int:post_id>/comments/<int:comment_id>/", PostCommentDetailView.as_view(), name="social-post-comment-detail"),
    path("posts/<int:post_id>/reaction/", PostReactionView.as_view(), name="social-post-reaction"),
    path("groups/", GroupListCreateView.as_view(), name="social-group-list-create"),
    path("groups/<int:group_id>/join/", GroupJoinView.as_view(), name="social-group-join"),
    path("groups/<int:group_id>/leave/", GroupLeaveView.as_view(), name="social-group-leave"),
    path("groups/<int:group_id>/members/", GroupMembershipListView.as_view(), name="social-group-members"),
    path("groups/<int:group_id>/feed/", GroupFeedView.as_view(), name="social-group-feed"),
    path("players/search/", PlayerSearchView.as_view(), name="social-player-search"),
    path("notifications/", NotificationsView.as_view(), name="social-notifications"),
    path("notifications/mark-seen/", NotificationsMarkSeenView.as_view(), name="social-notifications-mark-seen"),
    path("leaderboards/weekly/<str:path>/", WeeklyLeaderboardView.as_view(), name="social-leaderboard-weekly"),
    path("leaderboards/global/", GlobalLeaderboardView.as_view(), name="social-leaderboard-global"),
    path("leaderboards/armor/", ArmorLeaderboardView.as_view(), name="social-leaderboard-armor"),
    path("leaderboards/multiplier-streak/", MultiplierStreakLeaderboardView.as_view(), name="social-leaderboard-multiplier-streak"),
    path("leaderboards/output-monthly/", OutputMonthlyLeaderboardView.as_view(), name="social-leaderboard-output-monthly"),
]
