# Generated by Django 5.2.12 on 2026-03-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("runner", "Runner"),
                    ("gym", "Gym"),
                    ("discipline", "Discipline"),
                    ("tournament", "Tournament"),
                    ("75_hard", "75 Hard"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
