# Generated by Django 5.2.12 on 2026-04-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_update_player_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
    ]
