# Generated by Django 5.2.12 on 2026-04-05 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paths", "0004_session4_onboarding_models"),
        ("players", "0005_alter_player_last_active_date_alter_player_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodyjournal",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="elixirprogress",
            name="fill_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="elixirprogress",
            name="last_fill_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="elixirprogress",
            name="mercy_retained_fill_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outputlog",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warroomentry",
            name="morning_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warroomentry",
            name="evening_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warroomentry",
            name="morning_exp_awarded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warroomentry",
            name="evening_exp_awarded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warroomentry",
            name="bonus_exp_awarded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="warroomentry",
            name="same_day_bonus_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wisdomlog",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="chain_stage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="chain_unlocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="first_dollar_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="first_dollar_completed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="first_ten_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="first_hundred_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postfirstdollarchain",
            name="first_monthly_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ArmorSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_cracks", models.PositiveSmallIntegerField(default=0)),
                ("repaired_at", models.DateField(blank=True, null=True)),
                ("last_cracked_on", models.DateField(blank=True, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armor_system",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DarkNightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.TextField()),
                ("activated_on", models.DateField()),
                ("exp_awarded", models.PositiveIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dark_night_entries",
                        to="players.player",
                    ),
                ),
            ],
            options={"ordering": ["-activated_on"], "unique_together": {("player", "activated_on")}},
        ),
        migrations.CreateModel(
            name="KnightWeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("report_payload", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knight_weekly_reports",
                        to="players.player",
                    ),
                ),
            ],
            options={"ordering": ["-week_start", "-generated_at"], "unique_together": {("player", "week_start")}},
        ),
        migrations.CreateModel(
            name="TransmutationMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone_key", models.CharField(max_length=50)),
                ("achieved_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmutation_milestones",
                        to="players.player",
                    ),
                ),
            ],
            options={"ordering": ["-achieved_on"], "unique_together": {("player", "milestone_key")}},
        ),
    ]
