# Generated by Django 5.2.12 on 2026-04-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paths", "0005_bodyjournal_is_public_elixirprogress_fill_days_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountabilityPartner",
        ),
    ]
