# Generated by Django 5.2.12 on 2026-03-19 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_path"),
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="category",
            field=models.CharField(
                choices=[
                    ("fitness", "Fitness"),
                    ("discipline", "Discipline"),
                    ("productivity", "Productivity"),
                    ("health", "Health"),
                    ("recovery", "Recovery"),
                ],
                default="discipline",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="path_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "All Paths"),
                    ("runner", "Runner"),
                    ("gym", "Gym"),
                    ("discipline", "Discipline"),
                    ("tournament", "Tournament"),
                    ("75_hard", "75 Hard"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekdays", "Weekdays"),
                    ("weekly", "Weekly"),
                ],
                default="daily",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PlayerDailyQuestAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("assigned_exp_reward", models.PositiveIntegerField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quest_assignments",
                        to="players.player",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_assignments",
                        to="quests.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["quest_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "quest", "assignment_date"),
                        name="unique_player_quest_assignment_per_day",
                    )
                ],
            },
        ),
    ]
