# Generated by Django 5.2.12 on 2026-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_path"),
        ("quests", "0002_quest_category_quest_difficulty_quest_path_target_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playerdailyquestassignment",
            index=models.Index(
                fields=["player", "assignment_date"],
                name="quests_play_player__5ea607_idx",
            ),
        ),
    ]
