# Generated by Django 5.2.12 on 2026-04-03 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_update_player_model"),
        ("quests", "0006_add_quest_support_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuestLineupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_order", models.PositiveSmallIntegerField()),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("universal", "Universal"),
                            ("assigned", "Assigned"),
                            ("bonus", "Bonus"),
                            ("cross_path", "Cross Path"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("is_carried_over", models.BooleanField(default=False)),
                (
                    "selection_reason",
                    models.CharField(
                        choices=[
                            ("universal", "Universal"),
                            ("path_core", "Path Core"),
                            ("path_override", "Path Override"),
                            ("weekly_rhythm", "Weekly Rhythm"),
                            ("smart_score", "Smart Score"),
                            ("carry_over", "Carry Over"),
                            ("cross_path_bonus", "Cross Path Bonus"),
                            ("fallback", "Fallback"),
                            ("day1_starter", "Day 1 Starter"),
                            ("intention_adjustment", "Intention Adjustment"),
                        ],
                        default="path_core",
                        max_length=30,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[("up", "Thumbs Up"), ("down", "Thumbs Down")],
                        max_length=4,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["slot_order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="dailyquestlineup",
            options={"ordering": ["-date", "path"]},
        ),
        migrations.AlterUniqueTogether(
            name="dailyquestlineup",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="dailyintention",
            name="text",
        ),
        migrations.RemoveField(
            model_name="questpreference",
            name="weight",
        ),
        migrations.AddField(
            model_name="crosspathbonus",
            name="bonus_pair_key",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="dailycompletionsummary",
            name="bonus_exp_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailycompletionsummary",
            name="lineup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="quests.dailyquestlineup",
            ),
        ),
        migrations.AddField(
            model_name="dailycompletionsummary",
            name="path",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="dailycompletionsummary",
            name="quests_total",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailycompletionsummary",
            name="streak_status",
            field=models.CharField(default="maintained", max_length=30),
        ),
        migrations.AddField(
            model_name="dailyintention",
            name="intention",
            field=models.CharField(
                choices=[
                    ("full_send", "Full Send"),
                    ("steady", "Steady"),
                    ("recovery", "Recovery"),
                ],
                default="steady",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailyquestlineup",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="dailyquestlineup",
            name="intention",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_send", "Full Send"),
                    ("steady", "Steady"),
                    ("recovery", "Recovery"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailyquestlineup",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyquestlineup",
            name="path",
            field=models.CharField(
                choices=[
                    ("fitness_warrior", "Fitness Warrior"),
                    ("mindset_sage", "Mindset Sage"),
                    ("health_alchemist", "Health Alchemist"),
                    ("discipline_knight", "Discipline Knight"),
                    ("grind_visionary", "Grind Visionary"),
                ],
                default="fitness_warrior",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="dailyswap",
            name="path",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="questpreference",
            name="last_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questpreference",
            name="last_skipped",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questpreference",
            name="preference_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="crosspathbonus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailycompletionsummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyintention",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyquestlineup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyswap",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questfeedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questpreference",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyquestlineup",
            constraint=models.UniqueConstraint(
                fields=("player", "path", "date"),
                name="unique_daily_lineup_player_path_date",
            ),
        ),
        migrations.AddField(
            model_name="dailyquestlineupitem",
            name="lineup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="quests.dailyquestlineup",
            ),
        ),
        migrations.AddField(
            model_name="dailyquestlineupitem",
            name="quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lineup_items",
                to="quests.quest",
            ),
        ),
        migrations.AddField(
            model_name="dailyquestlineupitem",
            name="swapped_from_quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swapped_from_lineup_items",
                to="quests.quest",
            ),
        ),
        migrations.AddField(
            model_name="dailyswap",
            name="lineup_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swap_events",
                to="quests.dailyquestlineupitem",
            ),
        ),
        migrations.RemoveField(
            model_name="dailyquestlineup",
            name="lineup_date",
        ),
        migrations.RemoveField(
            model_name="dailyquestlineup",
            name="quest_ids",
        ),
        migrations.AddConstraint(
            model_name="dailyquestlineupitem",
            constraint=models.UniqueConstraint(
                fields=("lineup", "slot_order"), name="unique_lineup_slot_order"
            ),
        ),
    ]
