# Generated by Django 5.2.13 on 2026-04-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_alter_player_last_active_date_alter_player_timezone"),
        ("quests", "0007_dailyquestlineupitem_alter_dailyquestlineup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptiveDifficultyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("last_prompted_on", models.DateField(blank=True, null=True)),
                ("last_decision_on", models.DateField(blank=True, null=True)),
                (
                    "decision_source",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptive_difficulty_preference",
                        to="players.player",
                    ),
                ),
            ],
        ),
    ]
