# Generated by Django 5.2.13 on 2026-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0008_adaptivedifficultypreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquestlineupitem",
            name="is_cross_path_bonus",
            field=models.BooleanField(default=False),
        ),
    ]
