# Generated by Django 5.2.13 on 2026-05-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0009_dailyquestlineupitem_is_cross_path_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="questcompletion",
            name="exp_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
