# Generated by Django 5.2.12 on 2026-03-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="SocialGroup",
        ),
        migrations.AlterField(
            model_name="socialgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_social_groups",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="activityevent",
            name="related_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_events",
                to="social.socialgroup",
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="social.socialgroup",
            ),
        ),
        migrations.AlterField(
            model_name="socialpost",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="social.socialgroup",
            ),
        ),
    ]
