# Generated by Django 5.2.12 on 2026-04-05 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_alter_player_last_active_date_alter_player_timezone"),
        ("social", "0003_add_badges_and_boss"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountabilityPartnerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_accountability_requests",
                        to="players.player",
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_accountability_requests",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("from_player", models.F("to_player")), _negated=True),
                        name="social_accountability_request_not_self",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("from_player", "to_player"),
                        name="social_unique_pending_accountability_request_directional",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountabilityPartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "player_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountability_as_player_one",
                        to="players.player",
                    ),
                ),
                (
                    "player_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountability_as_player_two",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("player_one__lt", models.F("player_two"))),
                        name="social_accountability_ordered_pair",
                    ),
                    models.UniqueConstraint(
                        fields=("player_one", "player_two"),
                        name="social_unique_accountability_pair",
                    ),
                ],
            },
        ),
    ]
